name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Check import sorting with isort
      run: |
        isort --multi-line=3 --trailing-comma --check-only --diff --stdout src/
    - name: Lint with black
      run: |
        black --line-length=120 --check --diff src/
    - name: Lint with flake8
      run: |
        flake8 --extend-ignore=E203 --max-complexity=10 --max-line-length=120 src/
    - name: Test with pytest
      run: |
        py.test --cov=src --cov-config=.coveragerc --cov-fail-under=100 --cov-report=term-missing --showlocals --verbose src/tests/
